name: Deploy Portfolio to S3

on:
  push:
    branches:
      - main   # or 'master' if that's your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Sync files to S3
      - name: Deploy to S3
        uses: aws-actions/s3-sync@v2
        with:
          bucket: my-portfolio-poorvick      # your actual bucket name
          region: us-east-1
          source: .                          # means upload all files in repo
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
